<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Add payment method_monerisFrame</name>
   <tag></tag>
   <elementGuidId>3c6bc6f2-7ea7-47f5-a750-f7a5f98bae28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='monerisFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#monerisFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>monerisFrame</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>155px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://esqa.moneris.com/HPPtoken/index.php?id=htRCMC6HXLJLDPB&amp;css_body=font-family: Arial, Helvetica,sans-serif;background:transparent;&amp;css_textbox=border-radius:4px;border:2px solid rgb(74,68,160);width:100%;margin-bottom:24px;font-size:20px;font-weight:600;padding:8px 12px;outline:0;&amp;css_input_label=font-size:12px;position:relative;top:8px;left:6px;background:rgb(255,255,255);padding:3px 4px;color:rgb(66,66,66);font-weight:600;z-index:2;&amp;enable_exp=1&amp;css_textbox_exp=margin-bottom: 0;width:calc(50% - 12px);&amp;enable_cvd=1&amp;css_textbox_cvd=margin-bottom:0;width:50%;transform:translate(100%,-64px);&amp;css_label_cvd=display:inline-block;left:50%;transform:translate(6px,-3px);position:relative;top:-52px;&amp;display_labels=1&amp;cvd_label=CVC&amp;exp_label=Expiry(MMYY)&amp;pan_label=Card Number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;monerisFrame&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='monerisFrame']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
